package dao

import "godan/internal/pkg/database"

func AutoMigrate() error {
	queries := []string{
		`CREATE TABLE IF NOT EXISTS users (
			id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
			username VARCHAR(50) NOT NULL DEFAULT '',
			email VARCHAR(100) NOT NULL DEFAULT '',
			phone VARCHAR(20) NOT NULL DEFAULT '',
			password_hash VARCHAR(255) NOT NULL DEFAULT '',
			avatar VARCHAR(500) NOT NULL DEFAULT '',
			bio VARCHAR(500) NOT NULL DEFAULT '',
			birthday DATE NULL,
			gender TINYINT NOT NULL DEFAULT 0,
			status TINYINT NOT NULL DEFAULT 1,
			created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
			PRIMARY KEY (id),
			UNIQUE KEY uk_email (email),
			UNIQUE KEY uk_phone (phone)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,

		`CREATE TABLE IF NOT EXISTS follows (
			id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
			follower_id BIGINT UNSIGNED NOT NULL,
			followee_id BIGINT UNSIGNED NOT NULL,
			created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			PRIMARY KEY (id),
			UNIQUE KEY uk_follower_followee (follower_id, followee_id),
			INDEX idx_followee_id (followee_id)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,

		`CREATE TABLE IF NOT EXISTS user_blocklists (
			id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
			user_id BIGINT UNSIGNED NOT NULL,
			blocked_user_id BIGINT UNSIGNED NOT NULL,
			created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			PRIMARY KEY (id),
			UNIQUE KEY uk_user_blocked (user_id, blocked_user_id)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,

		`CREATE TABLE IF NOT EXISTS videos (
			id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
			user_id BIGINT UNSIGNED NOT NULL,
			title VARCHAR(200) NOT NULL DEFAULT '',
			description TEXT NOT NULL,
			cover_url VARCHAR(500) NOT NULL DEFAULT '',
			video_url VARCHAR(500) NOT NULL DEFAULT '',
			duration INT UNSIGNED NOT NULL DEFAULT 0,
			category_id INT UNSIGNED NOT NULL DEFAULT 0,
			tags JSON,
			file_size BIGINT UNSIGNED NOT NULL DEFAULT 0,
			status TINYINT NOT NULL DEFAULT 0,
			play_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
			like_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
			coin_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
			fav_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
			share_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
			created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
			PRIMARY KEY (id),
			INDEX idx_user_id (user_id),
			INDEX idx_category_id (category_id),
			INDEX idx_created_at (created_at)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,

		`CREATE TABLE IF NOT EXISTS video_likes (
			id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
			user_id BIGINT UNSIGNED NOT NULL,
			video_id BIGINT UNSIGNED NOT NULL,
			type TINYINT NOT NULL DEFAULT 1,
			created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			PRIMARY KEY (id),
			UNIQUE KEY uk_user_video (user_id, video_id)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

		`CREATE TABLE IF NOT EXISTS video_coins (
			id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
			user_id BIGINT UNSIGNED NOT NULL,
			video_id BIGINT UNSIGNED NOT NULL,
			count INT UNSIGNED NOT NULL DEFAULT 1,
			created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			PRIMARY KEY (id),
			INDEX idx_user_date (user_id, created_at),
			INDEX idx_video_id (video_id)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

		`CREATE TABLE IF NOT EXISTS favorite_folders (
			id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
			user_id BIGINT UNSIGNED NOT NULL,
			name VARCHAR(50) NOT NULL DEFAULT '',
			description VARCHAR(200) NOT NULL DEFAULT '',
			is_public TINYINT NOT NULL DEFAULT 0,
			count INT UNSIGNED NOT NULL DEFAULT 0,
			created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
			PRIMARY KEY (id),
			INDEX idx_user_id (user_id)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

		`CREATE TABLE IF NOT EXISTS favorite_items (
			id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
			folder_id BIGINT UNSIGNED NOT NULL,
			video_id BIGINT UNSIGNED NOT NULL,
			created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			PRIMARY KEY (id),
			UNIQUE KEY uk_folder_video (folder_id, video_id),
			INDEX idx_folder_id (folder_id)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

		`CREATE TABLE IF NOT EXISTS danmakus (
			id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
			video_id BIGINT UNSIGNED NOT NULL,
			user_id BIGINT UNSIGNED NOT NULL,
			content VARCHAR(200) NOT NULL DEFAULT '',
			color VARCHAR(20) NOT NULL DEFAULT '#FFFFFF',
			type TINYINT NOT NULL DEFAULT 0,
			position INT NOT NULL DEFAULT 0,
			created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			PRIMARY KEY (id),
			INDEX idx_video_position (video_id, position)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

		`CREATE TABLE IF NOT EXISTS activities (
			id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
			user_id BIGINT UNSIGNED NOT NULL,
			type TINYINT NOT NULL DEFAULT 0,
			target_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
			target_type TINYINT NOT NULL DEFAULT 0,
			created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			PRIMARY KEY (id),
			INDEX idx_user_created (user_id, created_at)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

		`CREATE TABLE IF NOT EXISTS notifications (
			id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
			user_id BIGINT UNSIGNED NOT NULL,
			type TINYINT NOT NULL DEFAULT 0,
			title VARCHAR(200) NOT NULL DEFAULT '',
			content VARCHAR(500) NOT NULL DEFAULT '',
			target_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
			is_read TINYINT NOT NULL DEFAULT 0,
			created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			PRIMARY KEY (id),
			INDEX idx_user_read (user_id, is_read, created_at)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

		`CREATE TABLE IF NOT EXISTS categories (
			id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
			name VARCHAR(50) NOT NULL DEFAULT '',
			sort INT NOT NULL DEFAULT 0,
			created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			PRIMARY KEY (id)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

		`CREATE TABLE IF NOT EXISTS reports (
			id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
			user_id BIGINT UNSIGNED NOT NULL,
			target_type TINYINT NOT NULL DEFAULT 0,
			target_id VARCHAR(50) NOT NULL DEFAULT '',
			reason VARCHAR(500) NOT NULL DEFAULT '',
			status TINYINT NOT NULL DEFAULT 0,
			created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
			PRIMARY KEY (id),
			INDEX idx_status (status)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	}

	// add role column to users (if not exists)
	database.DB.Exec("ALTER TABLE users ADD COLUMN role TINYINT NOT NULL DEFAULT 0")

	for _, q := range queries {
		if _, err := database.DB.Exec(q); err != nil {
			return err
		}
	}
	return nil
}
